
{{- if .Values.ingress.enabled }} 
{{- if .Values.ingress.httpsRedirect }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: "{{ .Values.app.name }}-http-to-https"
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
{{- end }}
{{- end }}
