apiVersion: v1
kind: Service
metadata:
  name: "{{ printf "%s-service" .Values.app.name }}"
spec:
  selector:
    {{- toYaml .Values.selectorLabels | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
